version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - errcheck  # TODO: Fix unchecked errors in a separate PR
  settings:
    misspell:
      locale: US
  exclusions:
    rules:
      - path: doc\.go
        linters:
          - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dray-io/dray
